font:
  normal:
    family: monospace
    style: Regular

  bold:
    family: monospace
    style: Bold

  italic:
    family: monospace
    style: Italic

  bold_italic:
    family: monospace
    style: Bold Italic

  size: 15

window:
    dimensions:
      columns: 120
      lines: 40

    opacity: 0.98      
env:
  WINIT_X11_SCALE_FACTOR: "1.0"
