distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 5.1.1
install_time: "Wed Sep  6 14:32:21 2023"
installation_id: "02e4076e-1294-41b6-8641-3150153cf2fb"
rime_version: 1.8.5